url: "aodhancorrigan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Aodhan Corrigan" # the name of your site, e.g. ACME Corp.
description: "Undergraduate Student in Physics at the University of Waterloo"
